sudo: false
language: python
python: "3.4"
env:
  matrix:
    - TESTENV=linters
    - TESTENV=py26
    - TESTENV=py27
    - TESTENV=py34
    - TESTENV=coveralls
install:
  - pip install tox
script: tox -e $TESTENV
branches:
  except:
    - /^\d/
notifications:
  email:
  - bubenkoff@gmail.com
