sudo: false
language: python
python: "3.8"
env:
  matrix:
    - TESTENV=linters
    - TESTENV=py38
    - TESTENV=py38-pytest-latest
    - TESTENV=coveralls
install:
  - pip install tox
script: tox -e $TESTENV
branches:
  except:
    - /^\d/
notifications:
  email:
  - bubenkoff@gmail.com
