sudo: false
language: python
python: "3.6"
env:
  matrix:
    - TESTENV=linters
    - TESTENV=py27
    - TESTENV=py36
    - TESTENV=coveralls
install:
  - pip install tox
script: tox -e $TESTENV
branches:
  except:
    - /^\d/
notifications:
  email:
  - bubenkoff@gmail.com
